'use client';
import { useMemo, useState } from 'react';
import { BookOpen, Check, ChevronDown, Clipboard, Code2, Menu, Search, Sigma, Sparkles, X } from 'lucide-react';

type Topic = { id:string; module:string; title:string; subtitle:string; color:string; essentials:string[]; formulas?:string[]; code?:string; warning?:string };
const topics:Topic[] = [
{id:'r-basics',module:'R Basics',title:'أساسيات R',subtitle:'Vectors · Data Frames · Logical Conditions',color:'mint',essentials:['<- للتخزين، و == للمقارنة','data$column للوصول إلى عمود','summary() و str() و names() لفحص البيانات','mean(condition) يعطي نسبة تحقق الشرط'],code:`x <- c(10, 20, 30)\nsummary(x)\nnames(data)\nstr(data)\nmean(data$Score >= 50)`},
{id:'descriptive',module:'Modules 2–4',title:'الإحصاء الوصفي',subtitle:'Center · Spread · Outliers · Visualization',color:'sky',essentials:['Mean يتأثر بالقيم الشاذة؛ Median أكثر مقاومة','SD يقيس التشتت حول المتوسط','IQR = Q3 − Q1','Histogram للرقمي، Bar Plot للفئوي، Scatter Plot لمتغيرين رقميين'],formulas:['IQR = Q₃ − Q₁','Lower = Q₁ − 1.5(IQR)','Upper = Q₃ + 1.5(IQR)'],code:`mean(x); median(x)\nvar(x); sd(x); IQR(x)\nhist(x)\nboxplot(x)\nplot(x, y)`},
{id:'probability',module:'Module 5',title:'قواعد الاحتمال',subtitle:'Events · Union · Intersection · Conditional',color:'violet',essentials:['Mutually Exclusive: لا يحدثان معًا','Independent: حدوث أحدهما لا يغير احتمال الآخر','Union = OR، Intersection = AND','Conditional Probability يضيّق فضاء العينة إلى حالات B'],formulas:['P(Aᶜ) = 1 − P(A)','P(A∪B) = P(A)+P(B)−P(A∩B)','Independent: P(A∩B)=P(A)P(B)','P(A|B)=P(A∩B)/P(B)']},
{id:'simulation',module:'Module 5',title:'المحاكاة في R',subtitle:'sample · table · prop.table · set.seed',color:'violet',essentials:['set.seed() يثبت النتائج العشوائية','replace = TRUE يسمح بتكرار النتيجة ويجعل السحبات مستقلة','table() للتكرارات وprop.table() للنسب','Law of Large Numbers: النسبة التجريبية تقترب من النظرية مع زيادة التجارب'],code:`set.seed(42)\ncoin <- sample(c("Head", "Tail"), 100, replace = TRUE)\ntable(coin)\nprop.table(table(coin))`},
{id:'binomial',module:'Module 5',title:'Binomial Distribution',subtitle:'Exact Probability · Simulation · Mean · Variance',color:'violet',essentials:['عدد ثابت من المحاولات، نتيجتان، p ثابت، والمحاولات مستقلة','dbinom لاحتمال عدد نجاحات محدد','pbinom للاحتمال التراكمي','rbinom للمحاكاة'],formulas:['P(X=k)=C(n,k)pᵏ(1−p)ⁿ⁻ᵏ','E(X)=np','Var(X)=np(1−p)'],code:`dbinom(19, size = 20, prob = 0.95)\npbinom(19, size = 20, prob = 0.95)\nx <- rbinom(1000, size = 20, prob = 0.95)\nbarplot(table(x))`},
{id:'normal',module:'Module 5',title:'Normal Distribution',subtitle:'Z-Score · pnorm · dnorm · Continuous Probability',color:'violet',essentials:['احتمال نقطة واحدة في المتغير المستمر يساوي صفرًا','pnorm للمساحة التراكمية، dnorm للكثافة والرسم','lower.tail = FALSE يعني المساحة يمين القيمة','بين قيمتين = التراكمي عند الأعلى ناقص التراكمي عند الأدنى'],formulas:['z = (x − μ) / σ','P(a<X<b) = F(b) − F(a)'],code:`z <- (x - mu) / sigma\npnorm(x, mean = mu, sd = sigma)\npnorm(x, mean = mu, sd = sigma, lower.tail = FALSE)\npnorm(b, mu, sigma) - pnorm(a, mu, sigma)`},
{id:'ci',module:'Module 6',title:'Confidence Intervals',subtitle:'Point Estimate · Standard Error · Margin of Error',color:'amber',essentials:['Point Estimate هو متوسط العينة','CI نطاق معقول لمتوسط المجتمع','زيادة Confidence Level توسّع الفترة','95% لا تعني أن 95% من البيانات داخل الفترة'],formulas:['x̄ ± t* × s/√n','SE = s/√n','Margin of Error = t* × SE'],code:`result <- t.test(accuracy, conf.level = 0.95)\nresult`},
{id:'hypothesis',module:'Module 6',title:'Hypothesis Testing',subtitle:'H₀ · Hₐ · α · p-value · Errors',color:'amber',essentials:['p ≤ α: Reject H₀','p > α: Fail to reject H₀ — لا نقول Accept','p-value ليست احتمال صحة H₀','Type I = False Positive؛ Type II = False Negative'],formulas:['α = 0.05 غالبًا','p ≤ α ⇒ Reject H₀','p > α ⇒ Fail to reject H₀'],warning:'Statistical significance لا تعني بالضرورة Practical significance.'},
{id:'ttests',module:'Module 6',title:'T-Tests الثلاثة',subtitle:'One-Sample · Independent · Paired',color:'amber',essentials:['One-Sample: مجموعة واحدة مقابل قيمة ثابتة','Independent: مجموعتان منفصلتان','Paired: نفس العناصر قبل وبعد','الـp-value تثبت وجود فرق؛ اتجاه المتوسطات يحدد تحسينًا أم تراجعًا'],code:`t.test(x, mu = 0.90)          # One-Sample\nt.test(modelA, modelB)          # Independent / Welch\nt.test(before, after, paired = TRUE)  # Paired`},
{id:'chi-square',module:'Module 6',title:'Chi-Square',subtitle:'Goodness-of-Fit · Independence · Expected Counts',color:'amber',essentials:['Goodness-of-Fit: متغير فئوي واحد مقابل توزيع متوقع','Independence: علاقة بين متغيرين فئويين','Expected Count = Row Total × Column Total / Grand Total','افحص أن Expected Counts تقريبًا 5 أو أكثر'],formulas:['χ² = Σ (O−E)²/E','E = (Row Total × Column Total) / Grand Total'],code:`chisq.test(observed, p = expected_probabilities)\n\nresult <- chisq.test(data$Variable1, data$Variable2)\nresult\nresult$expected`,warning:'Association لا تعني Causation. للقيم الصغيرة في جدول 2×2 استخدم fisher.test().'},
{id:'correlation',module:'Module 7',title:'Correlation',subtitle:'Scatter Plot · Pearson r · cor.test · Correlation Matrix',color:'rose',essentials:['r بين −1 و+1 ويصف القوة والاتجاه الخطي','cor() يعطي r فقط؛ cor.test() يضيف p-value وCI','H₀: ρ = 0','r = 0 لا ينفي علاقة منحنية، والـOutliers قد تشوّه r'],formulas:['−1 ≤ r ≤ 1','Simple Regression: R² = r²'],code:`plot(x, y, pch = 19)\ncor(x, y)\ncor.test(x, y)\n\nlibrary(dplyr)\nnumeric_data <- data %>% select(column1, column2, column3)\ncor_matrix <- cor(numeric_data, use = "complete.obs")`,warning:'Correlation does not imply causation.'},
{id:'regression',module:'Module 7',title:'Simple Linear Regression',subtitle:'Intercept · Slope · p-value · R² · Prediction',color:'rose',essentials:['Intercept: Y المتوقعة عندما X=0','Slope: تغير Y المتوقع لكل زيادة وحدة في X، on average','p-value للـSlope تختبر H₀: β₁=0','R² هي نسبة variability في Y التي يفسرها النموذج'],formulas:['Ŷ = b₀ + b₁X','Simple Regression: R² = r²'],code:`model <- lm(Exam_Score ~ Study_Hours, data = data)\nsummary(model)\n\nnew_student <- data.frame(Study_Hours = 10)\npredict(model, newdata = new_student)`},
{id:'multiple',module:'Module 7',title:'Multiple Regression',subtitle:'Holding Constant · Multiple Predictors · Prediction',color:'rose',essentials:['كل coefficient يفسَّر مع تثبيت بقية الـPredictors','المعاملات تُقدّر معًا، وليس كل واحد في اختبار منفصل','Multicollinearity تجعل فصل التأثيرات صعبًا','لا تتنبأ بعيدًا خارج نطاق البيانات'],formulas:['Ŷ = b₀ + b₁X₁ + b₂X₂ + … + bₖXₖ'],code:`model <- lm(\n  Exam_Score ~ Study_Hours + Attendance + Assignment_Score,\n  data = data\n)\nsummary(model)\n\nnew_student <- data.frame(Study_Hours = 10, Attendance = 90, Assignment_Score = 85)\npredict(model, newdata = new_student)`,warning:'افحص Linearity، Independence، Outliers، Extrapolation، Bias، ولا تدّعي Causation.'}
];
const testMap=[['متوسط واحد مقابل رقم','One-Sample t-test'],['متوسط مجموعتين منفصلتين','Independent t-test'],['نفس المجموعة قبل وبعد','Paired t-test'],['فئات مقابل توزيع متوقع','Chi-Square Goodness-of-Fit'],['علاقة بين متغيرين فئويين','Chi-Square Independence'],['علاقة بين متغيرين رقميين','Correlation'],['توقع Y رقمي من X واحد','Simple Regression'],['توقع Y رقمي من عدة X','Multiple Regression']];
function CopyButton({text}:{text:string}){const[copied,setCopied]=useState(false);return <button className="copy-button" onClick={()=>{navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1200)}}>{copied?<Check size={15}/>:<Clipboard size={15}/>} {copied?'تم النسخ':'نسخ'}</button>}
export default function Home(){const[query,setQuery]=useState('');const[activeModule,setActiveModule]=useState('الكل');const[open,setOpen]=useState<string[]>(['hypothesis','ttests','regression']);const[menuOpen,setMenuOpen]=useState(false);const modules=['الكل',...Array.from(new Set(topics.map(t=>t.module)))];const filtered=useMemo(()=>topics.filter(t=>(activeModule==='الكل'||t.module===activeModule)&&`${t.title} ${t.subtitle} ${t.module} ${t.essentials.join(' ')} ${t.formulas?.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[query,activeModule]);const toggle=(id:string)=>setOpen(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);return <main dir="rtl">
<header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Sigma size={20}/></span><span><b>Applied Stats</b><small>Exam Memory Page</small></span></a><nav className={menuOpen?'nav open':'nav'}><a href="#decision">اختيار الاختبار</a><a href="#topics">المواضيع</a><a href="#golden">قواعد ذهبية</a></nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></header>
<section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> مراجعة الليلة الأخيرة</div><h1>كل ما تحتاج أن تحفظه<br/><span>قبل امتحان Applied Statistics</span></h1><p>المفهوم، القانون، قرار الاختبار، وكود R — بدون حشو. ابحث عن أي مصطلح وافتح البطاقة التي تحتاجها فقط.</p><div className="search-box"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث: p-value، binomial، regression..."/>{query&&<button onClick={()=>setQuery('')}><X size={17}/></button>}</div></div><div className="decision-card"><span className="mini-label">قاعدة القرار الأشهر</span><div className="decision-line"><b>p ≤ 0.05</b><span>Reject H₀</span></div><div className="decision-line muted"><b>p &gt; 0.05</b><span>Fail to reject H₀</span></div><p>لا تقل أبدًا Accept H₀</p></div></section>
<section className="section" id="decision"><div className="section-heading"><span>01</span><div><h2>أي اختبار أستخدم؟</h2><p>ابدأ بشكل المتغيرات والسؤال، وليس باسم الدالة.</p></div></div><div className="test-grid">{testMap.map(([q,a])=><div className="test-row" key={q}><span>{q}</span><ChevronDown className="arrow" size={17}/><b>{a}</b></div>)}</div></section>
<section className="section" id="topics"><div className="section-heading"><span>02</span><div><h2>المادة كاملة كبطاقات حفظ</h2><p>{filtered.length} موضوع ظاهر — افتح البطاقة للتفاصيل والكود.</p></div></div><div className="filter-row">{modules.map(m=><button key={m} className={activeModule===m?'active':''} onClick={()=>setActiveModule(m)}>{m}</button>)}</div><div className="topic-list">{filtered.map(t=>{const expanded=open.includes(t.id);return <article className={`topic-card ${t.color} ${expanded?'expanded':''}`} key={t.id}><button className="topic-head" onClick={()=>toggle(t.id)}><span className="topic-icon">{t.code?<Code2 size={20}/>:<BookOpen size={20}/>}</span><span className="topic-title"><small>{t.module}</small><strong>{t.title}</strong><em>{t.subtitle}</em></span><ChevronDown className="chevron" size={22}/></button>{expanded&&<div className="topic-body"><div className="essentials"><h3>لازم تعرف</h3><ul>{t.essentials.map(i=><li key={i}>{i}</li>)}</ul></div>{t.formulas&&<div className="formula-box"><h3>القوانين</h3>{t.formulas.map(f=><code key={f}>{f}</code>)}</div>}{t.code&&<div className="code-wrap" dir="ltr"><div className="code-top"><span>R</span><CopyButton text={t.code}/></div><pre><code>{t.code}</code></pre></div>}{t.warning&&<div className="warning"><b>انتبه:</b> {t.warning}</div>}</div>}</article>})}{filtered.length===0&&<div className="empty">لا توجد نتيجة. جرّب كلمة أخرى أو اختر “الكل”.</div>}</div></section>
<section className="section golden-section" id="golden"><div className="section-heading"><span>03</span><div><h2>القواعد الذهبية</h2><p>الأخطاء التي تخسر علامات رغم أن الحساب صحيح.</p></div></div><div className="golden-grid">{[['01','Fail to reject ≠ Accept','عدم رفض الفرضية لا يثبت أنها صحيحة.'],['02','Association ≠ Causation','الارتباط أو الانحدار لا يثبت السبب والنتيجة.'],['03','Significant ≠ Important','الدلالة الإحصائية لا تضمن أهمية عملية كبيرة.'],['04','Check the data shape','رقمي أم فئوي؟ مستقل أم Paired؟ هذا يحدد الاختبار.'],['05','Read direction after p-value','الـp-value تقول إن كان هناك فرق؛ المتوسط أو المعامل يحدد الاتجاه.'],['06','Inspect before calculating','Scatter Plot وOutliers وExpected Counts قد تغيّر صلاحية النتيجة.']].map(([n,t,d])=><div className="golden-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<footer><Sigma size={18}/><span>Applied Statistics · Exam Memory Page</span><small>راجع الفكرة، ثم القانون، ثم كود R.</small></footer></main>}
